### ISSUE TITLE
Plugin configuration are empty.

### ISSUE THREAD

**Issue by JomW** [RecklessBoon/Macro-Deck-GPU-Z-Plugin#4]
Hi, I tried to run GPUZ and Macrodeck on my computer, after I installed the plugin, the plugin configuration is empty, I can only change the frequency.
I'm sorry for my English level, I'm a native Chinese speaker.

**Comment by DodecaDev-LLC** [comment]
Do you have GPU-Z running at the same time? The plugin queries the program
for available configuration options. If not, try running GPU-Z and then
opening the plugin config. Maybe even restart Macro Deck to be certain.

Hope that helps!

**Comment by JomW** [comment]
I reinstalled the .NET runtime library and restarted the system and it wooooorked!! I greatly appreciate your help ,thank you very much.
